version: "3.3"

services:
  database:
   container_name: testedjango
   image: postgres
   restart: always
   volumes:
    - ./.pgdata:/var/lib/postgresql/data
   environment:
   - LC_ALL=C.UTF-8
   - POSTGRES_PASSWORD=testedjango
   - POSTGRES_USER=testedjango
   ports:
   - 5434:5432